### ISSUE TITLE
C++  Exception in Asset code

### ISSUE THREAD

**Issue by diamante0018** [iw4x/iw4x-client#129] opened 2024-08-20 15:46 UTC
**What are you trying to do?**
Unknown, random user reported this issue

**What problem are you having?**
C++ Exception in the function `iw4x!Components::AssetHandler::FindAsset+0x90`
Minidump: https://discord.com/channels/1110531063161299074/1145458108190163014/1275479078820118650

**What have you tried so far?**
None

**What version of IW4x are you using?**
r4543

**Anything else we should know?**
No

**Comment by Rackover** [comment] 2024-08-26 12:30
The crash seems to be in `EvaluateExpression` unless I'm wrong
![image](https://github.com/user-attachments/assets/936bc6fc-b189-441d-9e63-41aa2ea30aff)

I'm checking the upmost minidump: iw4x-r4543-2-ga6a825cf-20240820002105.dmp


The second argument (the statement) to EvaluateExpression seems to be NULL
The callstack does not make more sense to me so I do not know where that NULLPTR came from.

Reproduction steps would be appreciated!

**Comment by Rackover** [comment] 2024-09-27 09:24
Most probably it was related to previous menu freeing code, since it often crashed in EvaluateExpression. closing for now

**Closed by Rackover** 2024-09-27 09:24 UTC
