### ISSUE TITLE
C++ Exception in menu code

### ISSUE THREAD

**Issue by diamante0018** [iw4x/iw4x-client#100] opened 2024-03-11 15:19 UTC
**What are you trying to do?**
Unknown, random user reported this issue

**What problem are you having?**
C++ Exception in the function `iw4x!Components::Menus::IsMenuVisible+0x63`
Minidump: https://discord.com/channels/1110531063161299074/1145458108190163014/1216765600928501913

**What have you tried so far?**
None

**What version of IW4x are you using?**
r4500

**Anything else we should know?**
No

**Comment by Rackover** [comment] 2024-06-20 09:05
Some menus in the menu list end up having a NULLPTR name, maybe because they're getting freed twice or used after free.
I dont like this at all :(
The bug can be reproduced, sometimes, by map restarting a few times. but not always. I'm not sure what triggers it deeply and dunno how to debug it except by printing every single menu alloc & free until the end of times

**Comment by Rackover** [comment] 2024-09-27 09:24
Fixed in r4611, _normally_

**Closed by Rackover** 2024-09-27 09:24 UTC
